
package org.esca.app.cadastros.fragmentos;

import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author elias
 */
public class JPanelTitle extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTitle
     */
    public JPanelTitle() {
        initComponents();

        setBackground(Color.BLACK);
        btnClose.setForeground(Color.GRAY);
        btnClose.setBorderPainted(false);
        btnClose.setFocusPainted(false);
        btnClose.setContentAreaFilled(false);

        
        btnClose.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btnClose.setContentAreaFilled(true);
                btnClose.setBackground(Color.RED);
                btnClose.setForeground(Color.WHITE);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnClose.setContentAreaFilled(false);
                btnClose.setForeground(Color.GRAY);
            }
        });

        lblTitle.setForeground(Color.WHITE);
        lblTitle.setFont(new Font("Roboto Black", Font.BOLD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Sample");
        add(lblTitle, java.awt.BorderLayout.CENTER);

        btnClose.setText("x");
        add(btnClose, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClose;
    public javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Color color1 = new Color(87, 52, 71);
        Color color2 = Color.black;
        Graphics2D graphics2D = (Graphics2D) g;
        GradientPaint p = new GradientPaint(0, 0, color1, getWidth(), 0, color2);
        graphics2D.setPaint(p);
        graphics2D.fillRect(0, 0, getWidth(), getHeight());
    }
}
